nodeLinker: node-modules

packageExtensions:
  "@nestjs/graphql@*":
    dependencies:
      apollo-server-core: "*"
  apollo-server-express@*:
    dependencies:
      express: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.3.0.cjs
