nodeLinker: node-modules

packageExtensions:
    '@nestjs/graphql@*':
        dependencies:
            apollo-server-core: '*'
    apollo-server-express@*:
        dependencies:
            express: '*'

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.3.0.cjs
